# Generated by Django 5.2.5 on 2025-09-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_author_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='ENTER A VALID TITLE', max_length=100, unique=True),
        ),
    ]
