# Generated by Django 5.2.5 on 2025-09-11 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 11, 19, 34, 13, 714079, tzinfo=datetime.timezone.utc)),
        ),
    ]
