# Generated by Django 5.2.5 on 2025-09-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_category_remove_article_pub_date_alter_article_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTest',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
