# Generated by Django 5.2.5 on 2025-09-13 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_mytest'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.DurationField(default=datetime.timedelta(days=23, seconds=77442)),
        ),
    ]
