# Generated by Django 5.2.5 on 2025-09-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_article_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.AddField(
            model_name='article',
            name='myfile',
            field=models.BinaryField(null=True),
        ),
    ]
