# Generated by Django 5.2.5 on 2025-10-03 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 3, 15, 30, 53, 205374, tzinfo=datetime.timezone.utc)),
        ),
    ]
