# Generated by Django 5.2.5 on 2025-10-03 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 3, 19, 32, 52, 603329, tzinfo=datetime.timezone.utc)),
        ),
    ]
