# Generated by Django 5.2.5 on 2025-10-15 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/articles/', verbose_name='انتخاب تصویر'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.IntegerField(null=True, verbose_name='بازدید'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 15, 7, 42, 3, 890946, tzinfo=datetime.timezone.utc)),
        ),
    ]
