# Generated by Django 5.2.5 on 2025-10-16 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_message_date_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='numbers',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 16, 1, 52, 19, 845809, tzinfo=datetime.timezone.utc)),
        ),
    ]
